// Builds a plain-text recap of a completed AURA workflow — used by the
// "Share summary" (clipboard) and "Download" actions on the results screen.
export function buildSummaryText({
  title,
  summary,
  metrics,
  outcomes,
  activity,
  prompt,
  interpretation,
  nextSteps,
}) {
  const lines = [];
  lines.push("AURA — Workflow Summary");
  lines.push("======================");
  lines.push("");
  if (prompt) lines.push(`Request: ${prompt}`);
  if (interpretation) lines.push(`Understood as: ${interpretation}`);
  lines.push("");
  lines.push(`Result: ${title || ""}`);
  if (summary) lines.push(summary);
  lines.push("");
  if (metrics && metrics.length) {
    lines.push("Key numbers:");
    metrics.forEach((m) => lines.push(`  • ${m.value} — ${m.label}`));
    lines.push("");
  }
  if (outcomes && outcomes.length) {
    lines.push("What was done:");
    outcomes.forEach((o) => {
      lines.push(`  • ${o.title}`);
      if (o.detail) lines.push(`    ${o.detail}`);
      if (o.link) lines.push(`    Link: ${o.link}${o.linkLabel ? ` (${o.linkLabel})` : ""}`);
      if (o.items && o.items.length)
        o.items.forEach((it) =>
          lines.push(`      - ${it.label}${it.detail ? ` — ${it.detail}` : ""}`)
        );
    });
    lines.push("");
  }
  if (activity && activity.length) {
    lines.push("Step-by-step activity:");
    activity.forEach((s, i) => {
      lines.push(`  ${i + 1}. [${s.tool}] ${String(s.action).replace(/…$/, "")}`);
      if (s.liveOutput) lines.push(`     ${s.liveOutput}`);
    });
    lines.push("");
  }
  if (nextSteps && nextSteps.length) {
    lines.push("Suggested next:");
    nextSteps.forEach((n) => lines.push(`  • ${n}`));
  }
  lines.push("");
  lines.push(`Generated by AURA · ${new Date().toLocaleString()}`);
  return lines.join("\n");
}